### ISSUE TITLE
My Account   page error

### ISSUE THREAD

**Issue by unallocatedman** [Unallocated/UASDrupal#198]
I had a day earlier entered bio information ..

then:
in Window "members",
( which is pretty much empty,
  I clicked on "My Account", top right corner, 

the following error appeared:

```
Notice: Undefined index: quantity in omega_views_mini_pager() (line 214 of /var/www/UASDrupal/docroot/profiles/unallocated/themes/omega/omega/includes/omega.theme.inc).
Notice: Undefined index: quantity in omega_views_mini_pager() (line 214 of /var/www/UASDrupal/docroot/profiles/unallocated/themes/omega/omega/includes/omega.theme.inc).
```

---

The user NAME and View-Edit window are there,
with pre-entered text, displayed OK.

The right side has "The Space is Open"
under that are the words:
"socket, Public Key Cryptography, openssl"   etc...

I have no idea what they are for .. or why they are there ..

**Comment by nhepner1** [comment]
Issue is no longer relevant - Omega tech has been removed from site.
