### ISSUE TITLE
Space doesn't close when clicked

### ISSUE THREAD

**Issue by unallocatedman** [Unallocated/UASDrupal#199]
When I click the big green button
that says "The Space is Open", 
it doesn't close the Space ....

Also, when I click the big Red button
that says "The Space is Closed", it doesn't 
open it...

Maybe it's only a status error.
Can someone tell me if the  front door
latches and iron bars fall across the clamps and locks
people in ? so that only a sonic screwdriver can
open it ?

**Comment by nhepner1** [comment]
It should not close the space. It is an indicator of whether the space is open or not. 

It is currently not working correctly on the server. Will create a new ticket to better describe existing issues.

**Comment by nhepner1** [comment]
New ticket has been created here: #205
