### ISSUE TITLE
What is the UASDrupal Development Platform and Target Platform?

### ISSUE THREAD

**Issue by Tektite** [Unallocated/UASDrupal#201]
What platform are you developing on and what is the target production platform?
//AJ

**Comment by nhepner1** [comment]
Site requirements and platform information are listed in the project README: https://github.com/Unallocated/UASDrupal/blob/7.x-1.x-dev/README.md

**Comment by Tektite** [comment]
Sorry, I'm nearsighted and having trouble finding the Platform information in the README.  I really need more specifics if I am going to try to setup a development and test server.

What is the Development Platform currently being used for developing and testing the master branch?  Linux? (distro please) Windows? (version please) OSX? (I won't be able to contribute)
What architecture?  32/64 bit?
Hardware:  Intel/AMD, Mac? Xen? VirtualBox? HyperV? Cloud?
Hardware specifics:  I really doubt your development and test servers are only 512MB RAM.

Once I know what hardware is required; and I know if I can put it together, then I'll ask for the specifics regarding the Development and Production servers' requisite development and operating software and configuration.

Of course, if the developers of this project are "just winging it" on "whatever" and there are no  repeatable configurations, I probably will not be able to contribute beyond infinite monkey testing.  I have no Drupal experience and no LAMP (or whatever support software is being used for Drupal on the platform) development experience, so this will be my first.  I might also just be simply be out of my league!  i.e. "the platform specific information should be obvious from the README" - but I just don't see it!
//AJ

**Comment by nhepner1** [comment]
Sure, Drupal (and most php applications) are meant to work cross-platform. I've worked on Windows systems and deployed to linux, and worked on linux and deployed to OSX - the more important piece is the web server, which performs the interpretation - of which we use Apache 2.0 or higher (I usually use 2.2). The binaries can also be translated across platforms, but there are installation packages for most systems.

This is why there are no hard platform requirements - the environment can be recreated by using the correct web server. The only limitation is that on Windows, the CLI (drush) is limited, and git tends to be more work.

The system that I use for development is LinuxMint (ubuntu), 64-bit, Intel i5. I have 8 gigs ram, but I have my php.ini memory limit set to 1024MB (which is pretty high).

The production servers are all Ubuntu VMs, hosted on AWS. There are three, which are currently identical, one to host Apache Solr, one for the UASDrupal application, and one for the database. Another will be added for Varnish to handle traffic spikes. This is hard to replicate on a local environment, and not very necessary.

Am I adequately answering your question?

**Comment by nhepner1** [comment]
Sorry, I keep hitting "close" button. I do not consider this issue closed.

**Comment by Tektite** [comment]
Thank you for staying with me on this issue and providing me with additional platform details.

Personally, all of my Linux machines need to be virtual.  I don't have any hardware I can dedicate to a Linux platform right now.

I haven't tried Mint before.  However, if Mint is Ubuntu/Debian based, can I use the following? (for my convenience):
Can I use Ubuntu Server (no GUI) 12.0.4.4 LTS/64 for target server?
Can I use Ubuntu 12.0.4.4 LTS/64 with XFCE desktop for development?
Ubuntu provides a standard LAMP stack which should comply with the requirements (I'll have to check the versions to make sure).

For Drupal, the README Requirements specifies:  "Drupal 7.x (currently included)"
The README Installation section states to "Install drupal as you would normally"

Please clarify:
Comment:  I'm confused by the "(currently included)" conflict with the "Install drupal as you would normally" for 2 reasons: 1 is, I never installed it before, so "normally" isn't applicable in my case; and 2.  The Requirements says Drupal 7.x is "currently included".

Questions:
Should I normally install Drupal by downloading it from Drupal.org?  Or should I normally install it from the UASDrupal project source?

If installing from Download from Drupal.org, which version should I download?
A) Should I download and install Drupal 7.x Development Release?  
or B) Should I download and install Drupal 7.26, current Recommended Release?

**Comment by unallocatedman** [comment]
At UAS, I think I can say that mirroring the alpha website is
a slightly different "project" than helping debug the website
superficially.  It's more part of learning web development
setup than locating and reporting user errors.

As part of that, I'd suggest D/L the rather large zip file,
and see whats in it.   If you don't want to unzip right away,
you should be able to use a normal linux file browser and the 
"file roller" code should allow you to see the innards ..
just by clicking ( it should start a text editor/window, or a
application selection link.. ).  I recall installing Drupal
separately.   As Rooster says, simply version 7.x for whatever your
platform is.  You are not developing Drupal so certainly not the developers
version, and 32 or 64 bit, if applicable, to whatever your VM is.
I used a ubuntu ( not mint ) on a UAS laptop, and after installing Drupal, 
I found it was 6.x.   I then either reinstalled or updated - don't remember
which, but, hey, something else to do ...  Note that at the time, the ubuntu
was an earlier version and Drupal 7.x wouldn't install on it...from the Drupal
site... so I needed to update the ubuntu OS itself...  Hey, as Rosanna Danna
from SNL says, it's ALWAYS something !!!!!

I asked about the 512Meg memory requirement listed, as I found it
a little confusing also.   The bottom line is it apparently is a minimum
requirement for XP running with the whole UAS web development environment.
So it includes both the OS and expected memory needs.  However, like
all numbers, it's a minimum.   Use some common sense WRT whatever
your OS is and the CPU speed. 

If you can't get to UAS on web dev nite, or another nite with A-KO,
you're probably stuck with trial and error at home...  which I know
can be a bit painful.   note: I haven't a clue how to use a VM,
so maybe your specific needs have to be, well, specific.

**Comment by Tektite** [comment]
Thanks!  Sorry if I seemed to push your buttons.  I was hoping there was a
cheat sheet around.  From what you describe - if you got it to work without
too many magic number tweaks inside config files; I should be able to get
it working.  At least now I know where I stand and I will revise my
strategy:  I'll do the trial and error method, document my success and
error resolutions, then ask specific questions when I get stuck.

Can you let me know which folder is the root folder for your production
server installation?  Or, this is probably simple for a Linux intermediate
- can you tell me how to make a sub folder to be a "root" folder?  for
  example, if I want to build GIT for Windows, the process expects the
  development tree's root to be "/" instead of something like
  "/home/aj/git/dev" - so there must be a way to map whatever my working
  folder tree is to start at a "/" root.  As you can tell from my
  description, I'm not sure enough what I'm talking about to google for it -
  I'm google-fu'd out for tonight.

//AJ

Although I like going to the space, my travel time is up to 1 hour each way
depending on traffic.  I can do a lot of trial and error in 2 hours
otherwise spent in the car.  I will also learn more in the trial and error
process.  What I don't like is wasting "error" time for dumb errors - which
I admit I experience a lot of when trying things without asking first!

On Sat, Mar 22, 2014 at 12:14 PM, unallocatedman
notifications@github.comwrote:

> At UAS, I think I can say that mirroring the alpha website is
> a slightly different "project" than helping debug the website
> superficially. It's more part of learning web development
> setup than locating and reporting user errors.
> 
> As part of that, I'd suggest D/L the rather large zip file,
> and see whats in it. If you don't want to unzip right away,
> you should be able to use a normal linux file browser and the
> "file roller" code should allow you to see the innards ..
> just by clicking ( it should start a text editor/window, or a
> application selection link.. ). I recall installing Drupal
> separately. As Rooster says, simply version 7.x for whatever your
> platform is. You are not developing Drupal so certainly not the developers
> version, and 32 or 64 bit, if applicable, to whatever your VM is.
> I used a ubuntu ( not mint ) on a UAS laptop, and after installing Drupal,
> I found it was 6.x. I then either reinstalled or updated - don't remember
> which, but, hey, something else to do ... Note that at the time, the ubuntu
> was an earlier version and Drupal 7.x wouldn't install on it...from the
> Drupal
> site... so I needed to update the ubuntu OS itself... Hey, as Rosanna Danna
> from SNL says, it's ALWAYS something !!!!!
> 
> I asked about the 512Meg memory requirement listed, as I found it
> a little confusing also. The bottom line is it apparently is a minimum
> requirement for XP running with the whole UAS web development environment.
> So it includes both the OS and expected memory needs. However, like
> all numbers, it's a minimum. Use some common sense WRT whatever
> your OS is and the CPU speed.
> 
> If you can't get to UAS on web dev nite, or another nite with A-KO,
> you're probably stuck with trial and error at home... which I know
> can be a bit painful. note: I haven't a clue how to use a VM,
> so maybe your specific needs have to be, well, specific.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/Unallocated/UASDrupal/issues/201#issuecomment-38355669
> .

## 

//AJ

**Comment by Tektite** [comment]
Here is my UASProject work so far until I figure out (by re-reading the project README and trial and error for any variances) what to do next.  Feel free to advise me.

http://www.unallocatedspace.org/wiki/UASDrupal

//AJ

**Comment by nhepner1** [comment]
UASDrupal platform now recommends https://github.com/nhepner1/project-base and the instructions within the README for local development. Does not work on windows.

**Comment by Tektite** [comment]
Thanks for the update!

//AJ
.-- ...-- .--. -- ..-

On Sun, Dec 6, 2015 at 1:03 AM, Nick notifications@github.com wrote:

> Closed #201 https://github.com/Unallocated/UASDrupal/issues/201.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Unallocated/UASDrupal/issues/201#event-483624176.

## 

//AJ
.-- ...-- .--. -- ..-
