### ISSUE TITLE
Create Delta layout for frontpage.

### ISSUE THREAD

**Issue by nhepner1** [Unallocated/UASDrupal#28]
Build delta theme to accomodate front-page layout options. 
- [x] Install delta and delta ui.
- [x] Create delta layout and context for frontpage.
- [x] Create exportables for delta layout and context, separately.

![Frontpage Delta](http://i1011.photobucket.com/albums/af232/anavrinman/frontpage_delta_zps8c27b024.png)

**Comment by Shep83** [comment]
Will complete the front page for logged in user in another ticket
