### ISSUE TITLE
Create view page for "Tutorials"

### ISSUE THREAD

**Issue by nhepner1** [Unallocated/UASDrupal#41]
Create the view for tutorials and export to a feature. This should be a page, attributed to the "/resources/tutorials" main menu item. This should be a sub-menu item of "Resources" This should be styled like the announcements view details on the front page. Reference the [Art Direction](https://github.com/Unallocated/UASDrupal/wiki/Art-Direction---Design-Proposal)
- [x] Create "Tutorials" view page
- [x] Assign main menu item in the view for "/resources/tutorials" with "Tutorials" text.
- [x] Make sure these fields are added: image, title, publication date, author, summary, "Read More >>" link. Reference the art direction and the "Announcements" view for field setup.
- [x] Create feature with view.
- [x] Add update hook to unallocated.install that enables the feature module.

**Comment by rweisser** [comment]
Finished everything except pull request.  Will show to Nick on web night.

**Comment by nhepner1** [comment]
This issue has been resolved and merged here: https://github.com/Unallocated/UASDrupal/pull/159
