### ISSUE TITLE
Create a views page for "Downloads"

### ISSUE THREAD

**Issue by nhepner1** [Unallocated/UASDrupal#42]
Create the view for Downloads and export to a feature. This should be a page, attributed to the "/resources/downloads" main menu item. This should be a sub-menu item of "Resources" This should be styled like the announcements view details on the front page. Reference the [Art Direction](https://github.com/Unallocated/UASDrupal/wiki/Art-Direction---Design-Proposal)
- [x] Create "Downloads" view page
- [x] Assign main menu item in the view for "/resources/downloads" with "Downloads" text.
- [x] Make sure these fields are added: image, title, publication date, author, summary, "Read More >>" link. Reference the art direction and the "Announcements" view for field setup.
- [x] Create feature with view.
- [x] Add update hook to unallocated.install that enables the feature module.

**Comment by rweisser** [comment]
Could not find publication date field.  Tried to add a new publication date field, but was not successful.

**Comment by rweisser** [comment]
I added a publication date field, which is visible in
http://uasdrupal.localhost/admin/structure/field-collections/field-download/fields,
but it does not appear in the field dropdown list for the view, in http://uasdrupal.localhost/admin/structure/views/view/downloads.

**Comment by rweisser** [comment]
Issued pull request.

**Comment by nhepner1** [comment]
This issue has been resolved and merged here: https://github.com/Unallocated/UASDrupal/pull/164
