### ISSUE TITLE
Update Organic Groups to most recent version.

### ISSUE THREAD

**Issue by nhepner1** [Unallocated/UASDrupal#51]
The current organic groups version has a security vulnerability. Because this is a major version release, this is a more complex task than simply upgrading with drush. Read release notes here: https://drupal.org/node/2059755

May require re-implementation of the "project" content type.

**Comment by rweisser** [comment]
I have done everything except push and issue a pull request.  However, something strange happened when I commited the removal of the old organic groups module.  I'll ask Nick tonight to look at the commit messages to make sure everything's okay.

**Comment by nhepner1** [comment]
This issue has been resolved and merged into the primary develpment branch
