### ISSUE TITLE
Set default URL in UAS checkin module

### ISSUE THREAD

**Issue by nhepner1** [Unallocated/UASDrupal#52]
The UAS checkin module uses a file stored at http://unallocatedspace.org/status to determine whether the space is open or not.

The default that is currently set is empty - the URL is not currently defined.

This is defined around line 50 in profiles/unallocated/modules/custom/uas_checkin/uas_checkin.module

```
    $form['uas_checkin_status_url'] = array(
        '#type'             => 'textfield',
        '#title'            => t('UAS Checkin Status URL'),
        '#default_value'    => variable_get('uas_checkin_status_url', ''),
    );
```

The #default_value property should be changed to use the above url as the default - like so:

```
    $form['uas_checkin_status_url'] = array(
        '#type'             => 'textfield',
        '#title'            => t('UAS Checkin Status URL'),
        '#default_value'    => variable_get('uas_checkin_status_url', 'http://unallocatedspace.org/status'),
    );
```

**Comment by rweisser** [comment]
Finished.  Pull request issued.

**Comment by nhepner1** [comment]
These changes have been made and merged into 7.x-1.x-dev
